### ISSUE TITLE
jnius.JavaException: Class not found b'android/bluetooth/BluetoothAdapter'

### ISSUE THREAD

**Issue by juasiepo** [ammar-bacha/Application_ISN_bluetooth_android#1]
Hi,

I am testing your code using python 3.7 and I am getting the following error.

python main.py 

[INFO   ] [Logger      ] Record log in /home/juan/.kivy/logs/kivy_19-11-07_8.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/home/juan/git/kivy/kivy_venv/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/home/juan/git/kivy/kivy_venv/bin/python"
[INFO   ] [Factory     ] 184 symbols loaded
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pygame(['text_pango'] ignored)
 Traceback (most recent call last):
   File "main.py", line 25, in <module>
     BluetoothAdapter = autoclass('android.bluetooth.BluetoothAdapter') ##découverte de périphériques, interroger une liste d'appareils (appairés)
   File "/home/juan/git/kivy/kivy_venv/lib/python3.7/site-packages/jnius/reflect.py", line 159, in autoclass
     c = find_javaclass(clsname)
   **File "jnius/jnius_export_func.pxi", line 26, in jnius.find_javaclass
 jnius.JavaException: Class not found b'android/bluetooth/BluetoothAdapter'**

Any Idea what I am doing wrong?

Thanks for your time

**Comment by ohspc89** [comment]
Hello, I do have the same issue here. Did you get to solve the issue?

**Comment by juasiepo** [comment]
@ohspc89 I couldn't make it work so I switched to https://github.com/b3b/able/
